import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { workspaceRoot } from "../intelligence/research-knowledge.mjs";
import { appendReplayEvent, loadResearchReplay, recordReplayCheckpoint, replayFrame, replayTimeline } from "../intelligence/research-replay.mjs";
const file=path.join(workspaceRoot,".research-index","research-replay.json");
fs.mkdirSync(path.dirname(file),{recursive:true});fs.rmSync(file,{force:true});
appendReplayEvent({sequence:1,timestamp:"2026-01-01T00:00:00Z",type:"task_started",taskId:"t1",topicId:"scope",summary:"start"});
appendReplayEvent({sequence:2,timestamp:"2026-01-01T00:00:01Z",type:"verification_passed",targetId:"review-e1",summary:"pass"});
recordReplayCheckpoint({sequence:2,graphState:{entityIds:["thesis","scope"],relationIds:[]},changeIntelligence:{changedEntityIds:["scope"]}});
appendReplayEvent({sequence:3,timestamp:"2026-01-01T00:00:02Z",type:"task_completed",taskId:"t1",summary:"done"});
const t=replayTimeline();assert.equal(t.latestSequence,3);assert.equal(t.sessions.at(-1).state,"completed");
const f=replayFrame(2);assert.equal(f.live,false);assert.deepEqual(f.graphState.entityIds,["thesis","scope"]);assert.equal(f.verification.entries[0].status,"passed");
assert.equal(loadResearchReplay().checkpoints.length,1);
fs.rmSync(file,{force:true});
console.log("Research Replay session/checkpoint reconstruction OK");
